import './globals.css'

export const metadata = {
  title: 'CRUD',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"/>
      </head>
      <body>{children}</body>
    </html>
  )
}
